RMAGICK_BYPASS_VERSION_TEST = true
require 'locomotive_cms'
require 'haml'
require 'mongoid'
require 'mongoid/railtie'
require 'mongoid/tree'
require 'kaminari'
require 'haml'
require 'liquid'
require 'cells'
